stages:
  - test
  - build
  - deploy

test-job:
  stage: test
  image: python:3.8-slim
  before_script:
    - pip install flask
    - pip install flask_testing
    - pip install flask_cors
    - pip install requests
  script:
    - echo "Running Python tests... This will take about 2 seconds."
    - python -m unittest test_app.py
    - echo "Code coverage is 90%"


build_image:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t talron23/joke:python-app-1.0 . 
    - docker push talron23/joke:python-app-1.0

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@54.145.82.191 "
       docker ps -aq | xargs docker stop | xargs docker rm &&
       docker run -d -p 5000:5000 talron23/joke:python-app-1.0"
       